sudo: false

language: php

php:
  - 7.3
  - 7.2
  - 7.1

install:
  - make vendor-bin/installed

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/behat
  - vendor/bin/readme-tester README.md
