sudo: false

language: php

matrix:
    include:
        - php: 7.0
        - php: 7.0
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer require hanneskod/readme-tester:dev-master phpspec/phpspec $COMPOSER_FLAGS --no-interaction

script:
    - vendor/bin/phpspec run --verbose
    - phpunit --verbose
