sudo: false

language: php

php:
    - 8.0
    - 7.4
    - 7.3
    - 7.2
    - 7.1

install:
    - make vendor/installed
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - make tools/phpspec tools/behat tools/readme-tester PHIVE_CMD="php phive.phar"

script:
    - tools/phpspec run --verbose
    - tools/behat
    - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then tools/readme-tester README.md ; fi
