sudo: false

language: php

matrix:
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer install --no-dev
  - composer global require phpspec/phpspec:^4 behat/behat:^3.3 hanneskod/readme-tester:^1.0@beta
  - export PATH=$PATH:$HOME/.composer/vendor/bin/

script:
  - phpspec run --verbose
  - behat --verbose
  - readme-tester test README.md
