sudo: false

language: php

matrix:
    include:
        - php: 7.0
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

install:
    - composer require phpspec/phpspec:^3.1 behat/behat:^3.2 --no-interaction

script:
    - vendor/bin/phpspec run --verbose
    - vendor/bin/behat --verbose
